## 
## Cadence First Encounter "v07.10-s075_1 ((32bit) 02/11/2008 19:57 (Linux 2.4))"
## Mon Mar  2 23:46:39 2009
## 
set sdc_version 1.4
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {refclk}]  -add  -name refclk -period 40 -waveform {0 20}
create_clock [get_pins {TEST_CONTROL_INST/m_rcc_clk}]  -add  -name m_rcc_clk -period 40 -waveform {0 20}
create_clock [get_pins {TEST_CONTROL_INST/m_ram_clk}]  -add  -name m_ram_clk -period 40 -waveform {0 20}
create_clock [get_pins {TEST_CONTROL_INST/m_clk}]  -add  -name m_clk -period 40 -waveform {0 20}
create_clock [get_pins {TEST_CONTROL_INST/m_dsram_clk}]  -add  -name m_dsram_clk -period 40 -waveform {0 20}
create_clock [get_pins {TEST_CONTROL_INST/m_digit_clk}]  -add  -name m_digit_clk -period 40 -waveform {0 20}
create_clock [get_pins {TEST_CONTROL_INST/m_spi_clk}]  -add  -name m_spi_clk -period 40 -waveform {0 20}
set_case_analysis 0 [get_ports {scan_en}]
set_case_analysis 0 [get_ports {test_mode}]
set_wire_load_mode enclosed
set_false_path -hold -from [get_ports scan_se]
set_false_path -setup -from [get_ports scan_se]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4.2 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {pllrst}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4.2 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {reset}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {int}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4.5 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[4]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {pllrst}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4.2 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {int}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {reset}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {reset}]
set_input_delay -add_delay 4.5 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[4]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {reset}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {pllrst}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {reset}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4.2 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {int}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {int}]
set_input_delay -add_delay 4.5 -clock [get_clocks {*}] [get_ports {port_pad_data_in[4]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {int}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {pllrst}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {int}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {reset}]
set_input_delay -add_delay 4.2 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[6]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[14]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[7]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {int}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[15]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[8]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_clk}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_in1}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {spi_data}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_in2}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {ibias}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_in[9]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {scan_en}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[10]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[0]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {scan_se}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4.5 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[4]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[3]}]
set_input_delay -add_delay 4.5 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[4]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {pllrst}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4.5 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[4]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[11]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_in[1]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_digit_clk}] [get_ports {pllrst}]
set_input_delay -add_delay 4 -clock [get_clocks {m_clk}] [get_ports {spi_fs}]
set_input_delay -add_delay 4 -clock [get_clocks {m_spi_clk}] [get_ports {reset}]
set_input_delay -add_delay 4.2 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_in[12]}]
set_input_delay -add_delay 4 -clock [get_clocks {m_rcc_clk}] [get_ports {pllrst}]
set_input_delay -add_delay 4.2 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_in[5]}]
set_input_delay -add_delay 4 -clock [get_clocks {refclk}] [get_ports {port_pad_data_in[13]}]
set_input_delay -add_delay 4.5 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_in[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[10]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[10]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[10]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[10]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[10]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[10]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {tdigit[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[11]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[12]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {vcom}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[13]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {vcop}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit_flag}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[14]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {scan_out1}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {scan_out2}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {port_pad_data_out[15]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_clk}] [get_ports {port_pad_data_out[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_dsram_clk}] [get_ports {tdigit[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[9]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {port_pad_data_out[0]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {refclk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_rcc_clk}] [get_ports {port_pad_data_out[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_ram_clk}] [get_ports {tdigit[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_digit_clk}] [get_ports {tdigit[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {m_spi_clk}] [get_ports {port_pad_data_out[10]}]
set_false_path  -from [get_ports {test_mode reset}] 
set_dont_use [get_lib_cells LOGIC1_X1]
set_dont_use [get_lib_cells FILLCELL_X4]
set_dont_use [get_lib_cells ram_256x16A]
set_dont_use [get_lib_cells LOGIC0_X1]
set_dont_use [get_lib_cells ANTENNA_X1]
set_dont_use [get_lib_cells FILLCELL_X2]
set_dont_use [get_lib_cells pllclk]
set_dont_use [get_lib_cells FILLCELL_X32]
set_dont_use [get_lib_cells FILLCELL_X1]
set_dont_use [get_lib_cells FILLCELL_X16]
set_dont_use [get_lib_cells FILLCELL_X8]
set_dont_use [get_lib_cells rom_512x16A]
set_dont_touch  [get_cells {SPI_INST/spare_233}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_2}]
set_dont_touch  [get_cells {ARB_INST/spare_45}]
set_dont_touch  [get_cells {SPI_INST/spare_200}]
set_dont_touch  [get_cells {SPI_INST/spare_43}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_13}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_3}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_0}]
set_dont_touch  [get_cells {SPI_INST/spare_133}]
set_dont_touch  [get_cells {ARB_INST/spare_31}]
set_dont_touch  [get_cells {DMA_INST/spare_7}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_46}]
set_dont_touch  [get_cells {SPI_INST/spare_3}]
set_dont_touch  [get_cells {SPI_INST/spare_7}]
set_dont_touch  [get_cells {ARB_INST/spare_18}]
set_dont_touch  [get_cells {SPI_INST/spare_12}]
set_dont_touch  [get_cells {SPI_INST/spare_221}]
set_dont_touch  [get_cells {DMA_INST/spare_38}]
set_dont_touch  [get_cells {SPI_INST/spare_240}]
set_dont_touch  [get_cells {DMA_INST/spare_15}]
set_dont_touch  [get_cells {SPI_INST/spare_106}]
set_dont_touch  [get_cells {SPI_INST/spare_208}]
set_dont_touch  [get_cells {SPI_INST/spare_140}]
set_dont_touch  [get_cells {ARB_INST/spare_39}]
set_dont_touch  [get_cells {SPI_INST/spare_15}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_9}]
set_dont_touch  [get_cells {SPI_INST/spare_37}]
set_dont_touch  [get_cells {ARB_INST/spare_9}]
set_dont_touch  [get_cells {ARB_INST/spare_25}]
set_dont_touch  [get_cells {SPI_INST/spare_127}]
set_dont_touch  [get_cells {SPI_INST/spare_229}]
set_dont_touch  [get_cells {DMA_INST/spare_45}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_4}]
set_dont_touch  [get_cells {SPI_INST/spare_248}]
set_dont_touch  [get_cells {DMA_INST/spare_22}]
set_dont_touch  [get_cells {ARB_INST/spare_11}]
set_dont_touch  [get_cells {SPI_INST/spare_113}]
set_dont_touch  [get_cells {SPI_INST/spare_215}]
set_dont_touch  [get_cells {DMA_INST/spare_31}]
set_dont_touch  [get_cells {SPI_INST/spare_234}]
set_dont_touch  [get_cells {DMA_INST/spare_0}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_20}]
set_dont_touch  [get_cells {SPI_INST/spare_10}]
set_dont_touch  [get_cells {ARB_INST/spare_46}]
set_dont_touch  [get_cells {SPI_INST/spare_201}]
set_dont_touch  [get_cells {SPI_INST/spare_44}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_30}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_1}]
set_dont_touch  [get_cells {SPI_INST/spare_134}]
set_dont_touch  [get_cells {ARB_INST/spare_32}]
set_dont_touch  [get_cells {SPI_INST/spare_143}]
set_dont_touch  [get_cells {DMA_INST/spare_8}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_47}]
set_dont_touch  [get_cells {SPI_INST/spare_30}]
set_dont_touch  [get_cells {SPI_INST/spare_8}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_27}]
set_dont_touch  [get_cells {SPI_INST/spare_120}]
set_dont_touch  [get_cells {ARB_INST/spare_19}]
set_dont_touch  [get_cells {SPI_INST/spare_222}]
set_dont_touch  [get_cells {DMA_INST/spare_39}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_33}]
set_dont_touch  [get_cells {SPI_INST/spare_241}]
set_dont_touch  [get_cells {DMA_INST/spare_16}]
set_dont_touch  [get_cells {SPI_INST/spare_107}]
set_dont_touch  [get_cells {SPI_INST/spare_209}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_14}]
set_dont_touch  [get_cells {SPI_INST/spare_141}]
set_dont_touch  [get_cells {ARB_INST/spare_4}]
set_dont_touch  [get_cells {SPI_INST/spare_16}]
set_dont_touch  [get_cells {SPI_INST/spare_38}]
set_dont_touch  [get_cells {SPI_INST/spare_128}]
set_dont_touch  [get_cells {ARB_INST/spare_26}]
set_dont_touch  [get_cells {SPI_INST/spare_23}]
set_dont_touch  [get_cells {DMA_INST/spare_46}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_40}]
set_dont_touch  [get_cells {SPI_INST/spare_249}]
set_dont_touch  [get_cells {DMA_INST/spare_23}]
set_dont_touch  [get_cells {SPI_INST/spare_114}]
set_dont_touch  [get_cells {ARB_INST/spare_12}]
set_dont_touch  [get_cells {SPI_INST/spare_216}]
set_dont_touch  [get_cells {DMA_INST/spare_32}]
set_dont_touch  [get_cells {SPI_INST/spare_235}]
set_dont_touch  [get_cells {DMA_INST/spare_1}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_25}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_21}]
set_dont_touch  [get_cells {SPI_INST/spare_100}]
set_dont_touch  [get_cells {ARB_INST/spare_47}]
set_dont_touch  [get_cells {SPI_INST/spare_202}]
set_dont_touch  [get_cells {SPI_INST/spare_45}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_31}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_10}]
set_dont_touch  [get_cells {SPI_INST/spare_135}]
set_dont_touch  [get_cells {ARB_INST/spare_33}]
set_dont_touch  [get_cells {SPI_INST/spare_144}]
set_dont_touch  [get_cells {DMA_INST/spare_9}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_48}]
set_dont_touch  [get_cells {SPI_INST/spare_31}]
set_dont_touch  [get_cells {SPI_INST/spare_9}]
set_dont_touch  [get_cells {SPI_INST/spare_121}]
set_dont_touch  [get_cells {ARB_INST/spare_2}]
set_dont_touch  [get_cells {SPI_INST/spare_223}]
set_dont_touch  [get_cells {DMA_INST/spare_4}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_34}]
set_dont_touch  [get_cells {SPI_INST/spare_242}]
set_dont_touch  [get_cells {DMA_INST/spare_17}]
set_dont_touch  [get_cells {SPI_INST/spare_108}]
set_dont_touch  [get_cells {SPI_INST/spare_21}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_15}]
set_dont_touch  [get_cells {SPI_INST/spare_142}]
set_dont_touch  [get_cells {ARB_INST/spare_40}]
set_dont_touch  [get_cells {SPI_INST/spare_17}]
set_dont_touch  [get_cells {SPI_INST/spare_39}]
set_dont_touch  [get_cells {SPI_INST/spare_129}]
set_dont_touch  [get_cells {ARB_INST/spare_27}]
set_dont_touch  [get_cells {SPI_INST/spare_230}]
set_dont_touch  [get_cells {DMA_INST/spare_47}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_41}]
set_dont_touch  [get_cells {SPI_INST/spare_25}]
set_dont_touch  [get_cells {DMA_INST/spare_24}]
set_dont_touch  [get_cells {SPI_INST/spare_115}]
set_dont_touch  [get_cells {ARB_INST/spare_13}]
set_dont_touch  [get_cells {SPI_INST/spare_217}]
set_dont_touch  [get_cells {DMA_INST/spare_33}]
set_dont_touch  [get_cells {SPI_INST/spare_236}]
set_dont_touch  [get_cells {DMA_INST/spare_10}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_22}]
set_dont_touch  [get_cells {SPI_INST/spare_101}]
set_dont_touch  [get_cells {ARB_INST/spare_48}]
set_dont_touch  [get_cells {SPI_INST/spare_203}]
set_dont_touch  [get_cells {SPI_INST/spare_46}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_32}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_11}]
set_dont_touch  [get_cells {SPI_INST/spare_136}]
set_dont_touch  [get_cells {ARB_INST/spare_34}]
set_dont_touch  [get_cells {SPI_INST/spare_0}]
set_dont_touch  [get_cells {SPI_INST/spare_145}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_49}]
set_dont_touch  [get_cells {SPI_INST/spare_32}]
set_dont_touch  [get_cells {SPI_INST/spare_122}]
set_dont_touch  [get_cells {ARB_INST/spare_20}]
set_dont_touch  [get_cells {SPI_INST/spare_224}]
set_dont_touch  [get_cells {DMA_INST/spare_40}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_35}]
set_dont_touch  [get_cells {SPI_INST/spare_243}]
set_dont_touch  [get_cells {DMA_INST/spare_18}]
set_dont_touch  [get_cells {SPI_INST/spare_109}]
set_dont_touch  [get_cells {SPI_INST/spare_210}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_16}]
set_dont_touch  [get_cells {ARB_INST/spare_41}]
set_dont_touch  [get_cells {SPI_INST/spare_18}]
set_dont_touch  [get_cells {SPI_INST/spare_4}]
set_dont_touch  [get_cells {ARB_INST/spare_28}]
set_dont_touch  [get_cells {SPI_INST/spare_13}]
set_dont_touch  [get_cells {DMA_INST/spare_48}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_42}]
set_dont_touch  [get_cells {SPI_INST/spare_26}]
set_dont_touch  [get_cells {DMA_INST/spare_25}]
set_dont_touch  [get_cells {ARB_INST/spare_14}]
set_dont_touch  [get_cells {SPI_INST/spare_116}]
set_dont_touch  [get_cells {SPI_INST/spare_218}]
set_dont_touch  [get_cells {DMA_INST/spare_34}]
set_dont_touch  [get_cells {SPI_INST/spare_237}]
set_dont_touch  [get_cells {DMA_INST/spare_11}]
set_dont_touch  [get_cells {ARB_INST/spare_49}]
set_dont_touch  [get_cells {SPI_INST/spare_102}]
set_dont_touch  [get_cells {SPI_INST/spare_204}]
set_dont_touch  [get_cells {SPI_INST/spare_47}]
set_dont_touch  [get_cells {SPI_INST/spare_137}]
set_dont_touch  [get_cells {ARB_INST/spare_35}]
set_dont_touch  [get_cells {SPI_INST/spare_1}]
set_dont_touch  [get_cells {SPI_INST/spare_146}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_5}]
set_dont_touch  [get_cells {SPI_INST/spare_33}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_12}]
set_dont_touch  [get_cells {ARB_INST/spare_21}]
set_dont_touch  [get_cells {SPI_INST/spare_123}]
set_dont_touch  [get_cells {SPI_INST/spare_225}]
set_dont_touch  [get_cells {DMA_INST/spare_41}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_36}]
set_dont_touch  [get_cells {SPI_INST/spare_244}]
set_dont_touch  [get_cells {DMA_INST/spare_19}]
set_dont_touch  [get_cells {SPI_INST/spare_11}]
set_dont_touch  [get_cells {SPI_INST/spare_211}]
set_dont_touch  [get_cells {DMA_INST/spare_28}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_17}]
set_dont_touch  [get_cells {ARB_INST/spare_42}]
set_dont_touch  [get_cells {SPI_INST/spare_19}]
set_dont_touch  [get_cells {SPI_INST/spare_40}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_28}]
set_dont_touch  [get_cells {ARB_INST/spare_29}]
set_dont_touch  [get_cells {SPI_INST/spare_130}]
set_dont_touch  [get_cells {DMA_INST/spare_49}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_43}]
set_dont_touch  [get_cells {SPI_INST/spare_27}]
set_dont_touch  [get_cells {DMA_INST/spare_26}]
set_dont_touch  [get_cells {ARB_INST/spare_15}]
set_dont_touch  [get_cells {SPI_INST/spare_117}]
set_dont_touch  [get_cells {SPI_INST/spare_219}]
set_dont_touch  [get_cells {DMA_INST/spare_35}]
set_dont_touch  [get_cells {SPI_INST/spare_238}]
set_dont_touch  [get_cells {DMA_INST/spare_12}]
set_dont_touch  [get_cells {SPI_INST/spare_103}]
set_dont_touch  [get_cells {ARB_INST/spare_5}]
set_dont_touch  [get_cells {SPI_INST/spare_205}]
set_dont_touch  [get_cells {SPI_INST/spare_48}]
set_dont_touch  [get_cells {SPI_INST/spare_138}]
set_dont_touch  [get_cells {ARB_INST/spare_36}]
set_dont_touch  [get_cells {SPI_INST/spare_147}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_6}]
set_dont_touch  [get_cells {SPI_INST/spare_34}]
set_dont_touch  [get_cells {SPI_INST/spare_124}]
set_dont_touch  [get_cells {ARB_INST/spare_22}]
set_dont_touch  [get_cells {SPI_INST/spare_226}]
set_dont_touch  [get_cells {DMA_INST/spare_42}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_37}]
set_dont_touch  [get_cells {SPI_INST/spare_245}]
set_dont_touch  [get_cells {DMA_INST/spare_2}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_26}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_23}]
set_dont_touch  [get_cells {SPI_INST/spare_110}]
set_dont_touch  [get_cells {ARB_INST/spare_0}]
set_dont_touch  [get_cells {SPI_INST/spare_212}]
set_dont_touch  [get_cells {DMA_INST/spare_29}]
set_dont_touch  [get_cells {SPI_INST/spare_231}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_18}]
set_dont_touch  [get_cells {ARB_INST/spare_43}]
set_dont_touch  [get_cells {SPI_INST/spare_2}]
set_dont_touch  [get_cells {SPI_INST/spare_41}]
set_dont_touch  [get_cells {SPI_INST/spare_131}]
set_dont_touch  [get_cells {ARB_INST/spare_3}]
set_dont_touch  [get_cells {DMA_INST/spare_5}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_44}]
set_dont_touch  [get_cells {SPI_INST/spare_28}]
set_dont_touch  [get_cells {DMA_INST/spare_27}]
set_dont_touch  [get_cells {SPI_INST/spare_118}]
set_dont_touch  [get_cells {ARB_INST/spare_16}]
set_dont_touch  [get_cells {SPI_INST/spare_22}]
set_dont_touch  [get_cells {DMA_INST/spare_36}]
set_dont_touch  [get_cells {SPI_INST/spare_239}]
set_dont_touch  [get_cells {DMA_INST/spare_13}]
set_dont_touch  [get_cells {SPI_INST/spare_104}]
set_dont_touch  [get_cells {ARB_INST/spare_6}]
set_dont_touch  [get_cells {SPI_INST/spare_206}]
set_dont_touch  [get_cells {SPI_INST/spare_49}]
set_dont_touch  [get_cells {SPI_INST/spare_139}]
set_dont_touch  [get_cells {ARB_INST/spare_37}]
set_dont_touch  [get_cells {SPI_INST/spare_148}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_7}]
set_dont_touch  [get_cells {SPI_INST/spare_35}]
set_dont_touch  [get_cells {SPI_INST/spare_125}]
set_dont_touch  [get_cells {ARB_INST/spare_23}]
set_dont_touch  [get_cells {SPI_INST/spare_227}]
set_dont_touch  [get_cells {DMA_INST/spare_43}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_38}]
set_dont_touch  [get_cells {SPI_INST/spare_246}]
set_dont_touch  [get_cells {DMA_INST/spare_20}]
set_dont_touch  [get_cells {SPI_INST/spare_111}]
set_dont_touch  [get_cells {ARB_INST/spare_1}]
set_dont_touch  [get_cells {SPI_INST/spare_213}]
set_dont_touch  [get_cells {DMA_INST/spare_3}]
set_dont_touch  [get_cells {SPI_INST/spare_232}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_19}]
set_dont_touch  [get_cells {ARB_INST/spare_44}]
set_dont_touch  [get_cells {SPI_INST/spare_20}]
set_dont_touch  [get_cells {SPI_INST/spare_42}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_29}]
set_dont_touch  [get_cells {SPI_INST/spare_132}]
set_dont_touch  [get_cells {ARB_INST/spare_30}]
set_dont_touch  [get_cells {DMA_INST/spare_6}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_45}]
set_dont_touch  [get_cells {SPI_INST/spare_29}]
set_dont_touch  [get_cells {SPI_INST/spare_6}]
set_dont_touch  [get_cells {SPI_INST/spare_119}]
set_dont_touch  [get_cells {ARB_INST/spare_17}]
set_dont_touch  [get_cells {SPI_INST/spare_220}]
set_dont_touch  [get_cells {DMA_INST/spare_37}]
set_dont_touch  [get_cells {SPI_INST/spare_24}]
set_dont_touch  [get_cells {DMA_INST/spare_14}]
set_dont_touch  [get_cells {SPI_INST/spare_105}]
set_dont_touch  [get_cells {ARB_INST/spare_7}]
set_dont_touch  [get_cells {SPI_INST/spare_207}]
set_dont_touch  [get_cells {SPI_INST/spare_5}]
set_dont_touch  [get_cells {SPI_INST/spare_14}]
set_dont_touch  [get_cells {ARB_INST/spare_38}]
set_dont_touch  [get_cells {SPI_INST/spare_149}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_8}]
set_dont_touch  [get_cells {SPI_INST/spare_36}]
set_dont_touch  [get_cells {ARB_INST/spare_8}]
set_dont_touch  [get_cells {SPI_INST/spare_126}]
set_dont_touch  [get_cells {ARB_INST/spare_24}]
set_dont_touch  [get_cells {SPI_INST/spare_228}]
set_dont_touch  [get_cells {DMA_INST/spare_44}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_39}]
set_dont_touch  [get_cells {SPI_INST/spare_247}]
set_dont_touch  [get_cells {DMA_INST/spare_21}]
set_dont_touch  [get_cells {TDSP_CORE_INST/spare_24}]
set_dont_touch  [get_cells {SPI_INST/spare_112}]
set_dont_touch  [get_cells {ARB_INST/spare_10}]
set_dont_touch  [get_cells {SPI_INST/spare_214}]
set_dont_touch  [get_cells {DMA_INST/spare_30}]

set_clock_uncertainty 0.6 -hold  -from [get_clocks {*}] -to [get_clocks {*}]
set_clock_uncertainty 0.4 -setup  -from [get_clocks {*}] -to [get_clocks {*}]
set_false_path -from [get_ports refclk]
set_false_path -to [get_pins {SPI_INST/bit_cnt_reg[3]/RN}]
set_false_path -to [get_pins {SPI_INST/bit_cnt_reg[1]/RN}]
set_false_path -hold -from [get_clocks {m_spi_clk}] -to [get_clocks {m_clk}]

set_propagated_clock  [get_clocks {*}]
